export const the = {
   color: {
      beige: '#eaba6b',
      purple: '#551a8b',
      sand: '#F4ECE6',
      white: '#ffffff',
   },
   method: {
      get: 'GET',
      post: 'POST',
      put: 'PUT',
   },
   npm: {
      packages: {
         'allow': 0,
         'allow-react': 0,
         'capitalize': 0,
         'clone': 0,
         'color': 0,
         'create-random-id': 0,
         'css3': 0,
         'get-cookies': 0,
         'get-url-parameters': 0,
         'is-a-regular-object': 0,
         'is-a-regular-object-react': 0,
         'local-storage': 0,
         'local-storage-is-available': 0,
         'looks-like-email': 0,
         'material-ui': 0,
         'session-storage': 0,
         'session-storage-is-available': 0,
         'string-contains': 0,
         'use-constructor': 0,
         'use-debouncer': 0,
         'use-synchronous-state': 0,
         'use-viewport': 0,
      },
   },
};
