export const jobs = [
   {
      description: <>Maintaining, extending, and re-architecting the in-house application that handled all outgoing marketing email communications (literally <i>billions</i> of emails)</>,
      employer: 'Amazon',
      technologies: 'JavaScript, Angular, React, Backbone, Node, jQuery, AWS',
      timeframe: '2022 - 2023',
      title: 'Frontend Engineer',
   },
   {
      description: 'Technical lead on a team developing user interfaces for Medicare.gov and HealthCare.gov',
      employer: 'SemanticBits',
      technologies: 'JavaScript, TypeScript, React, Node, Express, REST, HTML/CSS, Electron, Jenkins, GitHub',
      timeframe: '2020 - 2022',
      title: 'Senior Software Engineer',
   },
   {
      description: 'Full-stack developer responsible for building backend web services, and the SaaS frontend portals that consumed those services; High-volume environment coordinating sensitive data between major health insurance providers;',
      employer: 'Availity',
      technologies: 'Java, Oracle, JavaScript, Angular, React, jQuery, REST, HTML/CSS, Jenkins, Git',
      timeframe: '2017 - 2020',
      title: 'Developer III',
   },
   {
      description: 'Maintaining a large, legacy, SaaS Applicant Tracking System, while converting its backend to a series of REST services',
      employer: 'SilkRoad',
      technologies: 'ColdFusion, C#, JavaScript, jQuery, REST, MS-SQL, HTML/CSS, Perforce',
      timeframe: '2015 - 2017',
      title: 'Senior Software Engineer',
   },
   {
      description: 'Leading a team of developers initially focused on the implementation of a new content management system, and eventually tasked with supporting all functions on the public-facing website',
      employer: 'EverBank',
      technologies: 'C#, MS-SQL, JavaScript, jQuery, Knockout, Sitecore, Node, HTML/CSS, TFS',
      timeframe: '2012 - 2015',
      title: 'IT Manager',
   },
   {
      description: 'Creating a US-based business for an international outsourcing firm specializing in application development, design/graphics, business analysis, staffing, and quality assurance testing',
      employer: 'Insoft USA',
      technologies: 'PHP, JavaScript, jQuery, C#, MS-SQL, MySQL, HTML/CSS',
      timeframe: '2010 - 2012',
      title: 'Managing Partner',
   },
   {
      description: 'Building an IT department from scratch to support an $18M marketing company, including extensive budgeting and analysis of staffing and infrastructure',
      employer: 'MECLABS',
      technologies: 'PHP, MySQL, Google Analytics, JavaScript, jQuery, HTML/CSS',
      timeframe: '2007 - 2010',
      title: 'Director of Technology',
   },
   {
      description: 'Leading the transition from delivering customized, ad hoc software to a SaaS model based on formalized release management, including the implementation of new source control tools and the reorganization of development resources',
      employer: 'Vurv Technology',
      technologies: 'ColdFusion, MS-SQL, JavaScript, HTML/CSS',
      timeframe: '2004 - 2007',
      title: 'Director of Application Delivery',
   },
   {
      description: 'Developing custom applications to support the public website and internal/clinical objectives',
      employer: 'Nemours',
      technologies: 'ColdFusion, PHP, MS-SQL, HTML/CSS',
      timeframe: '2001 - 2004',
      title: 'Application Developer',
   },
   {
      description: 'I built numerous websites for clients.  I created a web-based, publicly-playable game for trading "shares" of athletes in real-time.  I built a boxing simulation.  I wrote automated currency-trading software.  I got my fingers into all sorts of exotically-flavored pies.',
      employer: 'Self-Employed',
      technologies: 'PHP, MySQL, HTML/CSS',
      timeframe: '1997 - 2001',
      title: 'Owner',
   },
   {
      description: 'I was a certified electronic technician, maintaining many of the same radars used at civilian airports.',
      employer: 'U.S. Air Force',
      technologies: '',
      timeframe: '1992 - 1997',
      title: 'Air Traffic Control Radar Technician',
   },
];
